# Generated by Django 2.2 on 2020-10-01 17:32

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0002_feedbackdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('courses', multiselectfield.db.fields.MultiSelectField(choices=[('Python', 'PYTHON'), ('Django', 'DJANGO'), ('Ui', 'UI'), ('RestAPI', 'REST API')], max_length=300)),
                ('trainer', multiselectfield.db.fields.MultiSelectField(choices=[('Shubham', 'SHUBHAM'), ('Uttam', 'UTTAM'), ('Harun', 'HARUN')], max_length=100)),
                ('branch', multiselectfield.db.fields.MultiSelectField(choices=[('Pune', 'PUNE'), ('Mumbai', 'MUMBAI'), ('Hyd', 'HYDERABAD'), ('Bang', 'BANGALORE')], max_length=100)),
                ('date', models.DateField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
            ],
        ),
    ]
