# Generated by Django 2.2 on 2020-10-01 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0003_contactdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactdata',
            old_name='trainer',
            new_name='trainers',
        ),
    ]
