# Generated by Django 2.2 on 2020-10-01 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0004_auto_20201001_2348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactdata',
            old_name='branch',
            new_name='branches',
        ),
    ]
