# Generated by Django 2.2 on 2020-10-02 10:23

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0006_coursesdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoursesData',
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='branches',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Pune', 'Pune'), ('Mumbai', 'Mumbai'), ('Hyderabad', 'Hyderabad'), ('Bangalore', 'Bangalore')], max_length=100),
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='courses',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Python', 'Python'), ('Django', 'Django'), ('UI', 'UI'), ('REST API', 'REST API')], max_length=300),
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='trainers',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Shubham', 'Shubham'), ('Uttam', 'Uttam'), ('Harun', 'Harun')], max_length=100),
        ),
    ]
