# Generated by Django 2.2 on 2020-10-02 10:43

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0007_auto_20201002_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdata',
            name='branches',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Pune', 'PUNE'), ('Mumbai', 'MUMBAI'), ('Hyd', 'HYDERABAD'), ('Bang', 'BANGALORE')], max_length=100),
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='courses',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Python', 'PYTHON'), ('Django', 'DJANGO'), ('Ui', 'UI'), ('RestAPI', 'REST API')], max_length=300),
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='date',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='gender',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='trainers',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Shubham', 'SHUBHAM'), ('Uttam', 'UTTAM'), ('Harun', 'HARUN')], max_length=100),
        ),
    ]
