# Generated by Django 2.2 on 2020-10-02 10:56

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0008_auto_20201002_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdata',
            name='courses',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Python', 'PYTHON'), ('Django', 'DJANGO'), ('Ui', 'UI'), ('RestAPI', 'REST API')], max_length=100),
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='trainers',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Shubham', 'SHUBHAM'), ('Uttam', 'UTTAM'), ('Harun', 'HARUN')], max_length=50),
        ),
    ]
