# Generated by Django 2.2 on 2020-10-05 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0011_coursesdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoursesData',
        ),
    ]
